### ISSUE TITLE
Script errors due to Neural Upgrade

### ISSUE THREAD

**Issue by thatdumbguy** [waicool20/WAI2K#23]
Dolls like M4A1, ST AR-15, etc. will crash the combat script, as it will select a 4-star filter to attempt to find them on swap.

**Comment by waicool20** [comment]
I havn't tried neural upgrade myself, does it change the rating of a doll?

**Comment by thatdumbguy** [comment]
Yes, the first stage of neural upgrade increases a t-doll's rarity. Note thiss only happens once at mod 1, not each mod. For example, M14 mod 1 is 4*... ST AR-15 mod 3 is 5*. 

 For now I'm using other dolls to drag but wanted to pass along that I noticed it. Thank you very much for your work!

**Comment by waicool20** [comment]
Support added in 90ee76a31c52fdcdac7e2cb063e65a1000dafb3f, tdolls with neural upgrade will now have a duplicate entry in the dragger list but with `+` appended to the name to indicate a modded tdoll eg. `M4A1+`

Also due to some configuration changes, options might get reset to default

Please test then close the issue if it works ok

**Comment by thatdumbguy** [comment]
I have tested 90ee76a with both ST AR-15+ and M4A1+ (the only MOD dolls I have). Swaps appear to be working properly. Thank you again for your assistance and work.
